services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Shanghai
    volumes:
      - /home/dalei/docker/obsidian/config:/config:rw
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
